package oktapam

import (
	"context"
	"strconv"
	"time"

	"github.com/okta/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/descriptions"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/okta/terraform-provider-oktapam/oktapam/client"
)

func dataSourceServerEnrollmentTokens() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceServerEnrollmentTokenRead,
		Schema: map[string]*schema.Schema{
			// Query parameter values
			attributes.ProjectName: {
				Type:        schema.TypeString,
				Required:    true,
				Description: descriptions.FilterProjectName,
			},
			// Return value
			attributes.ServerEnrollmentTokens: {
				Type:        schema.TypeList,
				Computed:    true,
				Description: descriptions.SourceServerEnrollmentTokens,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						attributes.ProjectName: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.ProjectName,
						},
						attributes.Token: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.Token,
						},
						attributes.ID: {
							Type:     schema.TypeString,
							Computed: true,
							// Description is autogenerated
						},
						attributes.IssuedAt: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.IssuedAt,
						},
						attributes.Description: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.Description,
						},
						attributes.CreatedByUser: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.CreatedByUser,
						},
					},
				},
			},
		},
	}
}

func dataSourceServerEnrollmentTokenRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)
	project := d.Get(attributes.ProjectName).(string)
	if project == "" {
		return diag.Errorf("%s cannot be blank", attributes.ProjectName)
	}
	tokensList, err := c.ListServerEnrollmentTokens(ctx, project)
	if err != nil {
		return diag.FromErr(err)
	}

	tokens := make([]map[string]interface{}, len(tokensList))
	for idx, token := range tokensList {
		tokens[idx] = token.ToResourceMap()
	}

	if err := d.Set(attributes.ServerEnrollmentTokens, tokens); err != nil {
		return diag.FromErr(err)
	}

	d.SetId(strconv.FormatInt(time.Now().Unix(), 10))
	return nil
}
