package oktapam

import (
	"context"
	"strconv"
	"time"

	"github.com/terraform-providers/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/terraform-providers/terraform-provider-oktapam/oktapam/constants/descriptions"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/terraform-providers/terraform-provider-oktapam/oktapam/client"
)

func dataSourceServiceUsers() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceServiceUsersRead,
		Schema: map[string]*schema.Schema{
			// Query parameter values
			attributes.Contains: {
				Type:        schema.TypeString,
				Optional:    true,
				Description: descriptions.FilterContains,
			},
			attributes.StartsWith: {
				Type:        schema.TypeString,
				Optional:    true,
				Description: descriptions.FilterStartsWith,
			},
			attributes.Status: {
				Type:        schema.TypeList,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Optional:    true,
				Description: descriptions.FilterStatus,
			},
			attributes.UserType: {
				Type:        schema.TypeString,
				Optional:    true,
				Description: descriptions.FilterUserType,
			},
			// Return value
			attributes.Users: {
				Type:        schema.TypeList,
				Computed:    true,
				Description: descriptions.SourceServiceUsers,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						attributes.Name: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.Name,
						},
						attributes.ID: {
							Type:     schema.TypeString,
							Computed: true,
							// Description is autogenerated
						},
						attributes.TeamName: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.TeamName,
						},
						attributes.ServerUserName: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.ServerUserName,
						},
						attributes.Status: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.Status,
						},
						attributes.DeletedAt: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.DeletedAt,
						},
						attributes.UserType: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: descriptions.UserType,
						},
					},
				},
			},
		},
	}
}

func dataSourceServiceUsersRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	c := m.(client.OktaPAMClient)
	var userType string

	// Get the query parameters for the request
	parameters := client.ListUsersParameters{}

	if contains, ok := d.GetOk(attributes.Contains); ok {
		parameters.Contains = contains.(string)
	}

	if startsWith, ok := d.GetOk(attributes.StartsWith); ok {
		parameters.StartsWith = startsWith.(string)
	}

	if s, ok := d.GetOk(attributes.Status); ok {
		statusI := s.([]interface{})
		status := make([]string, len(statusI))
		for idx, ri := range statusI {
			status[idx] = ri.(string)
		}
		parameters.Status = status
	} else {
		parameters.Status = make([]string, 0)
	}

	// Get the user type for the request
	if userTypeValue, ok := d.GetOk(attributes.UserType); ok {
		userType = userTypeValue.(string)
	}

	var usersList []client.User
	var err error

	// Based on data source user type, return corresponding type using corresponding endpoint
	// Note, in both endpoints `deleted` users are not returned
	switch userType {
	case string(client.UserTypeHuman):
		usersList, err = c.ListUsers(ctx, parameters)
		if err != nil {
			return diag.FromErr(err)
		}
	case string(client.UserTypeService):
		usersList, err = c.ListServiceUsers(ctx, parameters)
		if err != nil {
			return diag.FromErr(err)
		}
	case "":
		parameters.IncludeServiceUsers = "true"
		usersList, err = c.ListUsers(ctx, parameters)
		if err != nil {
			return diag.FromErr(err)
		}
	default:
		return diag.Errorf("%s is not a valid user type option", userType)
	}

	users := make([]map[string]interface{}, len(usersList))
	for idx, serviceUser := range usersList {
		users[idx] = serviceUser.ToResourceMap()
	}

	if err := d.Set(attributes.Users, users); err != nil {
		return diag.FromErr(err)
	}

	d.SetId(strconv.FormatInt(time.Now().Unix(), 10))
	return diags
}
