package oktapam

import (
	"context"
	"fmt"

	"github.com/okta/terraform-provider-oktapam/oktapam/constants/errors"

	"github.com/okta/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/descriptions"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/okta/terraform-provider-oktapam/oktapam/client"
)

func dataSourceServerEnrollmentToken() *schema.Resource {
	return &schema.Resource{
		Description: descriptions.SourceServerEnrollmentToken,
		ReadContext: dataSourceServerEnrollmentTokenFetch,
		Schema: map[string]*schema.Schema{
			attributes.ID: {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				// Description is autogenerated
			},
			attributes.ProjectName: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: descriptions.ProjectName,
			},
			attributes.Token: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.Token,
			},
			attributes.IssuedAt: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.IssuedAt,
			},
			attributes.Description: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.Description,
			},
			attributes.CreatedByUser: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.CreatedByUser,
			},
		},
	}
}

func dataSourceServerEnrollmentTokenFetch(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)

	id, projectName, err := getRequiredServerEnrollmentTokenAttributes(d)
	if err != nil {
		return diag.FromErr(err)
	}

	token, err := c.GetServerEnrollmentToken(ctx, projectName, id)
	if err != nil {
		return diag.FromErr(err)
	}

	if token != nil {
		d.SetId(createServerEnrollmentTokenResourceID(*token.Project, *token.ID))
		for key, value := range token.ToResourceMap() {
			d.Set(key, value)
		}
	} else {
		return diag.Errorf("%s %s does not exist", providerServerEnrollmentTokenKey, id)
	}

	return nil
}

func getRequiredServerEnrollmentTokenAttributes(d *schema.ResourceData) (string, string, error) {
	if d.Id() != "" {
		return parseServerEnrollmentTokenResourceID(d.Id())
	}

	id := getStringPtr(attributes.ID, d, false)
	if id == nil {
		return "", "", fmt.Errorf(errors.MissingAttributeError, attributes.ID)
	}

	projectName := getStringPtr(attributes.ProjectName, d, false)
	if projectName == nil {
		return "", "", fmt.Errorf(errors.MissingAttributeError, attributes.ProjectName)
	}

	return *id, *projectName, nil
}
