package oktapam

import (
	"context"

	"github.com/okta/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/descriptions"
	"github.com/okta/terraform-provider-oktapam/oktapam/logging"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/okta/terraform-provider-oktapam/oktapam/client"
)

func dataSourceGroup() *schema.Resource {
	return &schema.Resource{
		Description: descriptions.SourceGroup,
		ReadContext: dataSourceGroupFetch,
		Schema: map[string]*schema.Schema{
			attributes.Name: {
				Type:        schema.TypeString,
				Required:    true,
				Description: descriptions.Name,
			},
			attributes.ID: {
				Type:     schema.TypeString,
				Computed: true,
				// Description is autogenerated
			},
			attributes.DeletedAt: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.DeletedAt,
			},
			attributes.Roles: {
				Type: schema.TypeSet,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				Computed:    true,
				Description: descriptions.Roles,
			},
		},
	}
}

func dataSourceGroupFetch(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)
	name := d.Get(attributes.Name).(string)
	if name == "" {
		return diag.Errorf("%s cannot be blank", attributes.Name)
	}

	group, err := c.GetGroup(ctx, name, false)
	if err != nil {
		return diag.FromErr(err)
	}

	if group != nil {
		d.SetId(*group.Name)
		for key, value := range group.ToResourceMap() {
			d.Set(key, value)
		}
	} else {
		logging.Infof("group %s does not exist", name)
	}
	return nil
}
