package oktapam

import (
	"context"

	"github.com/okta/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/descriptions"
	"github.com/okta/terraform-provider-oktapam/oktapam/logging"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/okta/terraform-provider-oktapam/oktapam/client"
)

func dataSourceProject() *schema.Resource {
	return &schema.Resource{
		Description: descriptions.SourceProject,
		ReadContext: dataSourceProjectFetch,
		Schema: map[string]*schema.Schema{
			attributes.Name: {
				Type:        schema.TypeString,
				Required:    true,
				Description: descriptions.Name,
			},
			attributes.ID: {
				Type:     schema.TypeString,
				Computed: true,
				// Description is autogenerated
			},
			attributes.Team: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.TeamName,
			},
			attributes.NextUnixGID: {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: descriptions.NextUnixGID,
			},
			attributes.NextUnixUID: {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: descriptions.NextUnixUID,
			},
			attributes.CreateServerUsers: {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: descriptions.CreateServerUsers,
			},
			attributes.DeletedAt: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.DeletedAt,
			},
			attributes.ForwardTraffic: {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: descriptions.ForwardTraffic,
			},
			attributes.RDPSessionRecording: {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: descriptions.RDPSessionRecording,
			},
			attributes.RequirePreauthForCreds: {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: descriptions.RequirePreauthForCreds,
			},
			attributes.SSHSessionRecording: {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: descriptions.SSHSessionRecording,
			},
			attributes.GatewaySelector: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.GatewaySelector,
			},
			attributes.SSHCertificateType: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.SSHCertificateType,
			},
		},
	}
}

func dataSourceProjectFetch(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)
	name := d.Get(attributes.Name).(string)
	if name == "" {
		return diag.Errorf("%s cannot be blank", attributes.Name)
	}

	project, err := c.GetProject(ctx, name, false)
	if err != nil {
		return diag.FromErr(err)
	}

	if project != nil {
		d.SetId(*project.Name)
		for key, value := range project.ToResourceMap() {
			d.Set(key, value)
		}
	} else {
		logging.Infof("project %s does not exist", name)
	}
	return nil
}
