package oktapam

import (
	"context"
	"fmt"
	"github.com/okta/terraform-provider-oktapam/oktapam/logging"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/okta/terraform-provider-oktapam/oktapam/client"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/descriptions"
)

const (
	patchOperationAdd = "ADD"
)

//Project User Attribute Names
const (
	activeDirectoryIdentity             = "active_directory_identity"
	activeDirectoryPasswordlessIdentity = "active_directory_passwordless_identity"
	unixGid                             = "unix_gid"
	unixUid                             = "unix_uid"
	unixUserName                        = "unix_user_name"
	windowsUserName                     = "windows_user_name"
)

func resourceProjectUserAttribute() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceProjectUserAttributeCreate,
		ReadContext:   resourceProjectUserAttributeRead,
		//UpdateContext: resourceProjectUserAttributeUpdate,
		DeleteContext: resourceProjectUserAttributeDelete,
		Description:   descriptions.ResourceProjectUserAttribute,
		Schema: map[string]*schema.Schema{
			attributes.ID: {
				Type:     schema.TypeString,
				Computed: true,
				//Description is autogenerated
			},
			attributes.ProjectName: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: descriptions.Name,
			},
			attributes.UserName: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: descriptions.ProjectUserName,
			},
			attributes.ProjectUserAttributeName: {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				ValidateFunc: validation.StringInSlice([]string{
					activeDirectoryIdentity,
					activeDirectoryPasswordlessIdentity,
					unixUid,
					unixGid,
					unixUserName,
					windowsUserName,
				}, false),
			},
			attributes.ProjectUserAttributeValue: {
				Type: schema.TypeSet,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				Required: true,
			},
			attributes.ProjectUserAttributeIsManaged: {
				Type:     schema.TypeBool,
				Computed: true,
			},
			attributes.ProjectUserAttributeIsInherited: {
				Type:     schema.TypeBool,
				Computed: true,
			},
		},
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceProjectUserAttributeCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)

	projectName := d.Get(attributes.ProjectName).(string)
	userName := d.Get(attributes.UserName).(string)
	attrName := d.Get(attributes.ProjectUserAttributeName).(string)

	//Create user attribute patch operation api object
	operation := &client.UserAttributePatchOperation{
		Op:    patchOperationAdd,
		Path:  fmt.Sprintf("/attributes/%s/attribute_value", attrName),
		Value: d.Get(attributes.ProjectUserAttributeValue).(*schema.Set).List(),
	}
	operations := make([]*client.UserAttributePatchOperation, 1)
	operations[0] = operation
	userAttributePatch := &client.UserAttributePatch{
		Operations: operations,
	}

	if err := c.CreateProjectUserAttributes(ctx, projectName, userName, userAttributePatch); err != nil {
		return diag.FromErr(err)
	}

	//Call ListProjectAttributes to set the attribute id. Patch api to update project user attributes doesn't return attribute id
	if projectUserAttributes, err := c.ListProjectUserAttributes(ctx, projectName, userName); err != nil {
		//Get the attribute details by attribute name
		if attr, ok := projectUserAttributes.Attributes[attrName]; ok && attr.ID != nil {
			d.SetId(*attr.ID)
		} else {
			return diag.Errorf("project User Attribute %s not found", attrName)
		}
	} else {
		return diag.FromErr(err)
	}

	return resourceProjectUserAttributeRead(ctx, d, m)
}

func resourceProjectUserAttributeRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	c := m.(client.OktaPAMClient)

	projectName := d.Get(attributes.ProjectName).(string)
	userName := d.Get(attributes.UserName).(string)
	attrId := d.Id()
	attr, err := c.GetProjectUserAttribute(ctx, projectName, userName, attrId)
	if err != nil {
		return diag.FromErr(err)
	}

	if attr != nil && attr.Exists() {
		for key, value := range attr.ToResourceMap() {
			if err := d.Set(key, value); err != nil {
				return diag.FromErr(err)
			}
		}
	} else {
		logging.Infof("Attribute %s does not exist", attrId)
	}

	return diags
}

//func resourceProjectUserAttributeUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
//	c := m.(client.OktaPAMClient)
//
//	changed := false
//	updates := make(map[string]interface{})
//
//	changeableAttributes := []string{
//		attributes.ProjectUserAttributeValue,
//	}
//
//	for _, attribute := range changeableAttributes {
//		if d.HasChange(attribute) {
//			updates[attribute] = d.Get(attribute)
//			changed = true
//		}
//	}
//
//	if changed {
//		//Required attributes
//		projectName := d.Get(attributes.ProjectName).(string)
//		userName := d.Get(attributes.UserName).(string)
//		attrId := d.Id()
//
//		updateAttribute := client.UpdateAttribute{
//			AttributeName: d.Get(attributes.ProjectUserAttributeName).(string),
//			AttributeValue: updates[attributes.ProjectUserAttributeValue],
//		}
//
//		if err := c.UpdateProjectUserAttribute(ctx, projectName, userName, attrId, &updateAttribute) && err != nil {
//			return diag.FromErr(err)
//		}
//	}
//
//	return resourceProjectGroupRead(ctx, d, m)
//}

func resourceProjectUserAttributeDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	c := m.(client.OktaPAMClient)

	projectName := d.Get(attributes.ProjectName).(string)
	userName := d.Get(attributes.UserName).(string)
	attrId := d.Id()

	err := c.DeleteProjectUserAttribute(ctx, projectName, userName, attrId)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId("")
	return diags
}

