package oktapam

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	"github.com/okta/terraform-provider-oktapam/oktapam/client"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/descriptions"
	"github.com/okta/terraform-provider-oktapam/oktapam/logging"
	"github.com/okta/terraform-provider-oktapam/oktapam/utils"
)

func resourceCloudConnection() *schema.Resource {
	return &schema.Resource{
		Description:   descriptions.ResourceCloudConnection,
		ReadContext:   resourceCloudConnectionRead,
		CreateContext: resourceCloudConnectionCreate,
		DeleteContext: resourceCloudConnectionDelete,
		UpdateContext: resourceCloudConnectionUpdate,
		Schema: map[string]*schema.Schema{
			attributes.ID: {
				Type:     schema.TypeString,
				Computed: true,
				// Description is autogenerated
			},
			attributes.Name: {
				Type:        schema.TypeString,
				Required:    true,
				Description: descriptions.Name,
			},
			attributes.CloudConnectionProvider: {
				Type:        schema.TypeString,
				Required:    true,
				Description: descriptions.CloudConnectionProvider,
			},
			attributes.CloudConnectionDetails: {
				Type:        schema.TypeSet,
				Description: descriptions.CloudConnectionDetails,
				Required:    true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						attributes.CloudConnectionAccountId: {
							Type:     schema.TypeString,
							Required: true,
						},
						attributes.CloudConnectionExternalId: {
							Type:     schema.TypeString,
							Required: true,
						},
						attributes.CloudConnectionRoleARN: {
							Type:     schema.TypeString,
							Required: true,
						},
					},
				},
			},
		},
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceCloudConnectionRead(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	c := getLocalClientFromMetadata(m)
	id := d.Id()
	cloudConnection, err := c.GetCloudConnection(ctx, id, false)

	if err != nil {
		return diag.FromErr(err)
	}

	if cloudConnection == nil || utils.IsBlank(cloudConnection.ID) {
		logging.Debugf("id was blank")
		d.SetId("")
		return nil
	}

	for key, value := range cloudConnection.ToResourceMap() {
		logging.Debugf("setting %s to %v", key, value)
		if err := d.Set(key, value); err != nil {
			return diag.FromErr(err)
		}
	}

	return nil
}

func resourceCloudConnectionCreate(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	c := getLocalClientFromMetadata(m)
	cloudConnection := readCloudConnectionFromResource(d)

	result, err := c.CreateCloudConnection(ctx, cloudConnection)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(*result.ID)
	return resourceCloudConnectionRead(ctx, d, m)
}

func resourceCloudConnectionUpdate(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	var diags diag.Diagnostics
	c := getLocalClientFromMetadata(m)
	id := d.Id()
	cloudConnection  := readCloudConnectionFromResource(d)

	if id == "" {
		diags = append(diags, diag.Diagnostic{
			Severity: diag.Error,
			Summary:  "could not obtain cloud connection id from resource",
		})
	}

	if utils.IsBlank(cloudConnection.Name) {
		diags = append(diags, diag.Diagnostic{
			Severity: diag.Error,
			Summary:  "could not obtain name from resource",
		})
	}

	if diags != nil {
		return diags
	}

	cloudConnection.ID = &id

	if err := c.UpdateCloudConnection(ctx, cloudConnection); err != nil {
		return diag.FromErr(err)
	}

	return resourceCloudConnectionRead(ctx, d, m)
}

func resourceCloudConnectionDelete(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	c := getLocalClientFromMetadata(m)
	id := d.Id()

	err := c.DeleteCloudConnection(ctx, id)

	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId("")

	return nil
}

func readCloudConnectionFromResource(d *schema.ResourceData) client.CloudConnection {
	cloudConnection := client.CloudConnection{
		Name:     GetStringPtrFromResource(attributes.Name, d, true),
		Provider: GetStringPtrFromResource(attributes.CloudConnectionProvider, d, true),
		CloudConnectionDetails: &client.CloudConnectionDetails{
			AccountId:  GetStringPtrFromResource(attributes.CloudConnectionAccountId, d, true),
			ExternalId: GetStringPtrFromResource(attributes.CloudConnectionExternalId, d, true),
			RoleArn:    GetStringPtrFromResource(attributes.CloudConnectionRoleARN, d, true),
		},
	}

	return cloudConnection
}
