package oktapam

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/okta/terraform-provider-oktapam/oktapam/client"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/descriptions"
	"github.com/okta/terraform-provider-oktapam/oktapam/logging"
)

func resourceGateway() *schema.Resource {
	return &schema.Resource{
		Description:   descriptions.ResourceGatewaySetupToken,
		ReadContext:   resourceGatewayRead,
		UpdateContext: resourceGatewayUpdate,
		DeleteContext: resourceGatewayDelete,
		Schema: map[string]*schema.Schema{
			attributes.ID: {
				Type:     schema.TypeString,
				Computed: true,
				// Description is autogenerated
			},
			attributes.Name: {
				Type:        schema.TypeString,
				Description: descriptions.Name,
			},
			attributes.AccessAddress: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.AccessAddress,
			},
			attributes.DefaultAddress: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.DefaultAddress,
			},
			attributes.Description: {
				Type:        schema.TypeString,
				Description: descriptions.Description,
			},
			attributes.CloudProvider: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.CloudProvider,
			},
			attributes.RefuseConnections: {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: descriptions.RefuseConnections,
			},
			attributes.Labels: {
				Type: schema.TypeMap,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				Description: descriptions.Labels,
			},
		},
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceGatewayRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)

	gatewayID := d.Id()
	gateway, err := c.GetGateway(ctx, gatewayID)
	if err != nil {
		return diag.FromErr(err)
	}

	for key, value := range gateway.ToResourceMap() {
		logging.Debugf("setting %s to %v", key, value)
		d.Set(key, value)
	}

	return nil
}

func resourceGatewayUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)
	gatewayID := d.Get(attributes.ID).(string)

	changed := false
	updates := make(map[string]interface{})

	changeableAttributes := []string{
		attributes.Name,
		attributes.Description,
		attributes.Labels, // TODO: RawLabels on API side? Add more options?
	}

	for _, attribute := range changeableAttributes {
		if d.HasChange(attribute) {
			updates[attribute] = d.Get(attribute)
			changed = true
		}
	}

	if changed {
		err := c.UpdateGateway(ctx, gatewayID, updates)
		if err != nil {
			return diag.FromErr(err)
		}
	}

	return resourceProjectRead(ctx, d, m)
}

func resourceGatewayDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)

	id := d.Id()
	err := c.DeleteGateway(ctx, id)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId("")

	return nil
}
