package oktapam

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/terraform-providers/terraform-provider-oktapam/oktapam/client"
	"github.com/terraform-providers/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/terraform-providers/terraform-provider-oktapam/oktapam/constants/descriptions"
	"github.com/terraform-providers/terraform-provider-oktapam/oktapam/logging"
)

func resourceServiceUser() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceServiceUserCreate,
		ReadContext:   resourceServiceUserRead,
		UpdateContext: resourceServiceUserUpdate,
		DeleteContext: resourceServiceUserDelete,
		Description:   descriptions.ResourceServiceUser,
		Schema: map[string]*schema.Schema{
			attributes.Name: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: descriptions.Name,
			},
			attributes.ID: {
				Type:     schema.TypeString,
				Computed: true,
				// Description is autogenerated
			},
			attributes.TeamName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.TeamName,
			},
			attributes.ServerUserName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.ServerUserName,
			},
			attributes.Status: {
				Type:        schema.TypeString,
				Optional:    true, // TODO: Check this
				Description: descriptions.Status,
			},
			attributes.DeletedAt: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.DeletedAt,
			},
		},
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceServiceUserCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)
	userName := getStringPtr(attributes.Name, d, true)

	err := c.CreateServiceUser(ctx, *userName) // TODO: Maybe the username doesn't exist at this stage?
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(*userName)
	return resourceServiceUserRead(ctx, d, m)
}

func resourceServiceUserRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	c := m.(client.OktaPAMClient)

	userName := d.Id()
	serviceUser, err := c.GetServiceUser(ctx, userName)
	if err != nil {
		return diag.FromErr(err)
	}

	// Allow for deleted users, as they are soft-deleted
	if serviceUser != nil {
		d.SetId(*serviceUser.Name)
		for key, value := range serviceUser.ToResourceMap() {
			d.Set(key, value)
		}
	} else {
		logging.Infof("service user %s does not exist", userName)
	}

	return diags
}

func resourceServiceUserUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(client.OktaPAMClient)
	userName := d.Id()

	changed := false
	updates := make(map[string]interface{})

	changeableAttributes := []string{
		attributes.Status,
	}

	requiredAttributes := []string{
		attributes.Name,
	}

	for _, attribute := range changeableAttributes {
		if d.HasChange(attribute) {
			updates[attribute] = d.Get(attribute)
			changed = true
		}
	}

	for _, attribute := range requiredAttributes {
		updates[attribute] = d.Get(attribute)
	}

	if changed {
		su, err := client.ServiceUserFromMap(updates)
		if err != nil {
			return diag.FromErr(err)
		} else if su == nil {
			return diag.Errorf("could not create service user from supplied values")
		}

		// NOTE: possible that other fields must be included in the update
		err = c.UpdateServiceUser(ctx, userName, su)
		if err != nil {
			return diag.FromErr(err)
		}
	}
	d.SetId(userName)
	return resourceServiceUserRead(ctx, d, m)
}

func resourceServiceUserDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	c := m.(client.OktaPAMClient)
	userName := d.Id()

	err := c.DeleteServiceUser(ctx, userName)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId("")
	return diags
}
