// Code generated by policygen. DO NOT EDIT!

package client

import (
	"encoding/json"
	"fmt"
)

type DatabaseBasedResourceSubSelectorType string

const (
	DatabaseBasedResourceSelectorType     = ResourceSelectorType("database_based_resource")
	DatabaseLabelsDatabaseSubSelectorType = DatabaseBasedResourceSubSelectorType("database_labels")
	PasswordCheckoutDatabasePrivilegeType = PrivilegeType("password_checkout_database")
)

// Privileges: password_checkout_database

var _ SecurityPolicyRulePrivilege = &PasswordCheckoutDatabasePrivilege{}

type PasswordCheckoutDatabasePrivilege struct {
	Enabled *bool `json:"password_checkout_database"`
}

func (p *PasswordCheckoutDatabasePrivilege) ValidForResourceType(resourceSelectorType ResourceSelectorType) bool {
	return resourceSelectorType == DatabaseBasedResourceSelectorType
}

var _ json.Unmarshaler = &DatabaseBasedResourceSubSelectorContainer{}

type DatabaseBasedResourceSubSelectorContainer struct {
	SelectorType DatabaseBasedResourceSubSelectorType `json:"selector_type"`
	Selector     DatabaseBasedResourceSubSelector     `json:"selector"`
}

func (c *DatabaseBasedResourceSubSelectorContainer) UnmarshalJSON(data []byte) error {
	tmp := struct {
		SelectorType DatabaseBasedResourceSubSelectorType `json:"selector_type"`
		Selector     json.RawMessage                      `json:"selector"`
	}{}

	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}

	c.SelectorType = tmp.SelectorType
	switch tmp.SelectorType {
	case DatabaseLabelsDatabaseSubSelectorType:
		c.Selector = &DatabaseLabelsBasedSubSelector{}
	default:
		return fmt.Errorf("received unknown sub-selector type: %s", tmp.SelectorType)
	}
	if err := json.Unmarshal(tmp.Selector, c.Selector); err != nil {
		return err
	}

	return nil
}

// Sub-Selectors: database_labels

type DatabaseLabelsDatabaseSelector struct {
	Labels map[string]string `json:"labels"`
}

var _ DatabaseBasedResourceSubSelector = &DatabaseLabelsBasedSubSelector{}

type DatabaseLabelsBasedSubSelector struct {
	DatabaseSelector *DatabaseLabelsDatabaseSelector `json:"database_selector"`
}

func (*DatabaseLabelsBasedSubSelector) DatabaseBasedResourceSubSelectorType() DatabaseBasedResourceSubSelectorType {
	return DatabaseLabelsDatabaseSubSelectorType
}

func (d *DatabaseLabelsBasedSubSelector) UnmarshalJSON(data []byte) error {
	tmp := struct {
		DatabaseSelector *DatabaseLabelsDatabaseSelector `json:"database_selector"`
	}{}

	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}

	d.DatabaseSelector = tmp.DatabaseSelector
	return nil
}

var _ SecurityPolicyRuleResourceSelector = &DatabaseBasedResourceSelector{}

type DatabaseBasedResourceSelector struct {
	Selectors []DatabaseBasedResourceSubSelectorContainer `json:"selectors"`
}

func (*DatabaseBasedResourceSelector) ResourceSelectorType() ResourceSelectorType {
	return DatabaseBasedResourceSelectorType
}

type DatabaseBasedResourceSubSelector interface {
	DatabaseBasedResourceSubSelectorType() DatabaseBasedResourceSubSelectorType
	ToResourceMap() map[string]any
}
