package sdkv2

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/okta/terraform-provider-oktapam/oktapam/client"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/descriptions"
	"github.com/okta/terraform-provider-oktapam/oktapam/logging"
)

func resourceGatewaySetupToken() *schema.Resource {
	return &schema.Resource{
		Description:   descriptions.ResourceGatewaySetupToken,
		CreateContext: resourceGatewaySetupTokenCreate,
		ReadContext:   resourceGatewaySetupTokenRead,
		DeleteContext: resourceGatewaySetupTokenDelete,
		Schema: map[string]*schema.Schema{
			attributes.ID: {
				Type:     schema.TypeString,
				Computed: true,
				// Description is autogenerated
			},
			attributes.CreatedAt: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.CreatedAt,
			},
			attributes.Description: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: descriptions.Description,
			},
			attributes.Labels: {
				Type: schema.TypeMap,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				Required:    true,
				ForceNew:    true,
				Description: descriptions.Labels,
			},
			attributes.Token: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.Token,
			},
		},
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceGatewaySetupTokenRead(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	var diags diag.Diagnostics
	c := client.GetLocalClientFromMetadata(m)

	tokenID := d.Id()
	token, err := c.GetGatewaySetupToken(ctx, tokenID)
	if err != nil {
		return diag.FromErr(err)
	}

	if token == nil {
		logging.Debugf("setup token id was blank")
		d.SetId("")
		return nil
	}

	for key, value := range token.ToResourceMap() {
		logging.Debugf("setting %s to %v", key, value)
		if err := d.Set(key, value); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}

	return diags
}

func resourceGatewaySetupTokenCreate(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	c := client.GetLocalClientFromMetadata(m)

	description := GetStringPtrFromResource(attributes.Description, d, true)
	labels := d.Get(attributes.Labels).(map[string]any)

	labelsMap := make(map[string]string, len(labels))

	for k, v := range labels {
		labelsMap[k] = fmt.Sprint(v)
	}

	tokenSpec := client.GatewaySetupToken{
		Description: description,
		Details:     &client.GatewaySetupTokenLabelDetails{Labels: labelsMap},
	}
	if createdToken, err := c.CreateGatewaySetupToken(ctx, tokenSpec); err != nil {
		return diag.FromErr(err)
	} else if createdToken == nil {
		d.SetId("")
	} else {
		d.SetId(*createdToken.ID)
	}

	return resourceGatewaySetupTokenRead(ctx, d, m)
}

func resourceGatewaySetupTokenDelete(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	c := client.GetLocalClientFromMetadata(m)

	id := d.Id()
	err := c.DeleteGatewaySetupToken(ctx, id)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId("")

	return nil
}
