package sdkv2

import (
	"context"
	"fmt"
	"strings"

	"github.com/okta/terraform-provider-oktapam/oktapam/client"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/attributes"
	"github.com/okta/terraform-provider-oktapam/oktapam/constants/descriptions"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/okta/terraform-provider-oktapam/oktapam/logging"
	"github.com/okta/terraform-provider-oktapam/oktapam/utils"
)

func resourceResourceGroupServerEnrollmentToken() *schema.Resource {
	return &schema.Resource{
		Description:   descriptions.ResourceResourceGroupServerEnrollmentToken,
		CreateContext: resourceResourceGroupServerEnrollmentTokenCreate,
		ReadContext:   resourceResourceGroupServerEnrollmentTokenRead,
		DeleteContext: resourceResourceGroupServerEnrollmentTokenDelete,
		Schema: map[string]*schema.Schema{
			attributes.ID: {
				Type:     schema.TypeString,
				Computed: true,
				// Description is autogenerated
			},
			attributes.ResourceGroup: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: descriptions.ResourceGroupID,
			},
			attributes.Project: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: descriptions.ProjectID,
			},
			attributes.Description: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: descriptions.Description,
			},
			attributes.Token: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.Token,
			},
			attributes.CreatedByUser: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.CreatedByUser,
			},
			attributes.IssuedAt: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: descriptions.IssuedAt,
			},
		},
		Importer: &schema.ResourceImporter{
			StateContext: importResourceResourceGroupServerEnrollmentTokenState,
		},
	}
}

func resourceResourceGroupServerEnrollmentTokenRead(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	c := client.GetLocalClientFromMetadata(m)

	serverEnrollmentTokenID := d.Id()
	resourceGroupID := d.Get(attributes.ResourceGroup).(string)
	projectID := d.Get(attributes.Project).(string)

	token, err := c.GetResourceGroupServerEnrollmentToken(ctx, resourceGroupID, projectID, serverEnrollmentTokenID)
	if err != nil {
		return diag.FromErr(err)
	}

	if token == nil || utils.IsBlank(token.ID) {
		logging.Debugf("token id was blank")
		d.SetId("")
		return nil
	}

	for key, value := range token.ToResourceMap() {
		logging.Debugf("setting %s to %v", key, value)
		if err := d.Set(key, value); err != nil {
			return diag.FromErr(err)
		}
	}

	return nil
}

func resourceResourceGroupServerEnrollmentTokenCreate(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	c := client.GetLocalClientFromMetadata(m)

	resourceGroupID := d.Get(attributes.ResourceGroup).(string)
	projectID := d.Get(attributes.Project).(string)
	description := d.Get(attributes.Description).(string)

	token, err := c.CreateResourceGroupServerEnrollmentToken(ctx, resourceGroupID, projectID, description)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(*token.ID)

	return resourceResourceGroupServerEnrollmentTokenRead(ctx, d, m)
}

func resourceResourceGroupServerEnrollmentTokenDelete(ctx context.Context, d *schema.ResourceData, m any) diag.Diagnostics {
	c := client.GetLocalClientFromMetadata(m)

	serverEnrollmentTokenID := d.Id()
	resourceGroupID := d.Get(attributes.ResourceGroup).(string)
	projectID := d.Get(attributes.Project).(string)

	err := c.DeleteResourceGroupServerEnrollmentToken(ctx, resourceGroupID, projectID, serverEnrollmentTokenID)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId("")

	return nil
}

func parseResourceGroupServerEnrollmentTokenResourceID(resourceId string) (string, string, string, error) {
	split := strings.Split(resourceId, "/")
	if len(split) != 3 {
		return "", "", "", fmt.Errorf("expected format: <resource_group_id>/<project_id>/<id>, received: %s", resourceId)
	}
	return split[0], split[1], split[2], nil
}

func importResourceResourceGroupServerEnrollmentTokenState(ctx context.Context, d *schema.ResourceData, meta any) ([]*schema.ResourceData, error) {
	// d.Id() here is the last argument passed to the `terraform import RESOURCE_TYPE.RESOURCE_NAME RESOURCE_ID` command
	// Id provided for import is in the format <resource_group_id>/<project_id>/<id>.
	// Both project name and ASA resource UUID is required to read resource back
	resourceGroupID, projectID, serverEnrollmentTokenID, err := parseResourceGroupServerEnrollmentTokenResourceID(d.Id())
	if err != nil {
		return nil, fmt.Errorf("invalid resource import specifier; %w", err)
	}
	if err := d.Set(attributes.ResourceGroup, resourceGroupID); err != nil {
		return nil, err
	}
	if err := d.Set(attributes.Project, projectID); err != nil {
		return nil, err
	}
	//Set id to ASA resource UUID
	d.SetId(serverEnrollmentTokenID)

	return []*schema.ResourceData{d}, nil
}
