// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_resource_group

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ResourceGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"delegated_resource_admin_groups": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Required:            true,
							Description:         "The UUID of the object",
							MarkdownDescription: "The UUID of the object",
						},
						"name": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "The human-readable name of the object",
							MarkdownDescription: "The human-readable name of the object",
						},
						"type": schema.StringAttribute{
							Optional: true,
							Computed: true,
							Validators: []validator.String{
								stringvalidator.OneOf(
									"user",
									"user_group",
									"server",
									"project",
									"sudo_entitlement",
									"resource_group",
									"secret_folder",
									"secret",
								),
							},
						},
					},
					CustomType: DelegatedResourceAdminGroupsType{
						ObjectType: types.ObjectType{
							AttrTypes: DelegatedResourceAdminGroupsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required:            true,
				Description:         "An array of OPA groups that own this Resource Group. This param is only available to users with the `resource_admin` role.",
				MarkdownDescription: "An array of OPA groups that own this Resource Group. This param is only available to users with the `resource_admin` role.",
			},
			"description": schema.StringAttribute{
				Required:            true,
				Description:         "A description of the Resource Group",
				MarkdownDescription: "A description of the Resource Group",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The UUID of the Resource Group",
				MarkdownDescription: "The UUID of the Resource Group",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Resource Group",
				MarkdownDescription: "The name of the Resource Group",
			},
		},
	}
}

type ResourceGroupModel struct {
	DelegatedResourceAdminGroups types.List   `tfsdk:"delegated_resource_admin_groups"`
	Description                  types.String `tfsdk:"description"`
	Id                           types.String `tfsdk:"id"`
	Name                         types.String `tfsdk:"name"`
}

var _ basetypes.ObjectTypable = DelegatedResourceAdminGroupsType{}

type DelegatedResourceAdminGroupsType struct {
	basetypes.ObjectType
}

func (t DelegatedResourceAdminGroupsType) Equal(o attr.Type) bool {
	other, ok := o.(DelegatedResourceAdminGroupsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DelegatedResourceAdminGroupsType) String() string {
	return "DelegatedResourceAdminGroupsType"
}

func (t DelegatedResourceAdminGroupsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DelegatedResourceAdminGroupsValue{
		Id:                               idVal,
		Name:                             nameVal,
		DelegatedResourceAdminGroupsType: typeVal,
		state:                            attr.ValueStateKnown,
	}, diags
}

func NewDelegatedResourceAdminGroupsValueNull() DelegatedResourceAdminGroupsValue {
	return DelegatedResourceAdminGroupsValue{
		state: attr.ValueStateNull,
	}
}

func NewDelegatedResourceAdminGroupsValueUnknown() DelegatedResourceAdminGroupsValue {
	return DelegatedResourceAdminGroupsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDelegatedResourceAdminGroupsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DelegatedResourceAdminGroupsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DelegatedResourceAdminGroupsValue Attribute Value",
				"While creating a DelegatedResourceAdminGroupsValue value, a missing attribute value was detected. "+
					"A DelegatedResourceAdminGroupsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DelegatedResourceAdminGroupsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DelegatedResourceAdminGroupsValue Attribute Type",
				"While creating a DelegatedResourceAdminGroupsValue value, an invalid attribute value was detected. "+
					"A DelegatedResourceAdminGroupsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DelegatedResourceAdminGroupsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DelegatedResourceAdminGroupsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DelegatedResourceAdminGroupsValue Attribute Value",
				"While creating a DelegatedResourceAdminGroupsValue value, an extra attribute value was detected. "+
					"A DelegatedResourceAdminGroupsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DelegatedResourceAdminGroupsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDelegatedResourceAdminGroupsValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewDelegatedResourceAdminGroupsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDelegatedResourceAdminGroupsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewDelegatedResourceAdminGroupsValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewDelegatedResourceAdminGroupsValueUnknown(), diags
	}

	return DelegatedResourceAdminGroupsValue{
		Id:                               idVal,
		Name:                             nameVal,
		DelegatedResourceAdminGroupsType: typeVal,
		state:                            attr.ValueStateKnown,
	}, diags
}

func NewDelegatedResourceAdminGroupsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DelegatedResourceAdminGroupsValue {
	object, diags := NewDelegatedResourceAdminGroupsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDelegatedResourceAdminGroupsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DelegatedResourceAdminGroupsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDelegatedResourceAdminGroupsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDelegatedResourceAdminGroupsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDelegatedResourceAdminGroupsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDelegatedResourceAdminGroupsValueMust(DelegatedResourceAdminGroupsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DelegatedResourceAdminGroupsType) ValueType(ctx context.Context) attr.Value {
	return DelegatedResourceAdminGroupsValue{}
}

var _ basetypes.ObjectValuable = DelegatedResourceAdminGroupsValue{}

type DelegatedResourceAdminGroupsValue struct {
	Id                               basetypes.StringValue `tfsdk:"id"`
	Name                             basetypes.StringValue `tfsdk:"name"`
	DelegatedResourceAdminGroupsType basetypes.StringValue `tfsdk:"type"`
	state                            attr.ValueState
}

func (v DelegatedResourceAdminGroupsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.DelegatedResourceAdminGroupsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DelegatedResourceAdminGroupsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DelegatedResourceAdminGroupsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DelegatedResourceAdminGroupsValue) String() string {
	return "DelegatedResourceAdminGroupsValue"
}

func (v DelegatedResourceAdminGroupsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"id":   basetypes.StringType{},
			"name": basetypes.StringType{},
			"type": basetypes.StringType{},
		},
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.DelegatedResourceAdminGroupsType,
		})

	return objVal, diags
}

func (v DelegatedResourceAdminGroupsValue) Equal(o attr.Value) bool {
	other, ok := o.(DelegatedResourceAdminGroupsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.DelegatedResourceAdminGroupsType.Equal(other.DelegatedResourceAdminGroupsType) {
		return false
	}

	return true
}

func (v DelegatedResourceAdminGroupsValue) Type(ctx context.Context) attr.Type {
	return DelegatedResourceAdminGroupsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DelegatedResourceAdminGroupsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}
