steps:
  - name: "Unit Tests"
    command: "./scripts/ci-tests.sh"
    key: "test"
    timeout_in_minutes: 20
    agents:
      queue: dev-elastic-ci
  - name: "Acceptance Tests"
    if: build.pull_request.repository.fork == null || build.pull_request.labels includes 'run-acceptance'
    command: "./scripts/ci-acceptance-tests.sh"
    key: "acceptance-test"
    timeout_in_minutes: 20
    agents:
      queue: dev-elastic-ci
  - name: "Compile"
    command: "./scripts/ci-compile.sh"
    key: "Compile"
    timeout_in_minutes: 20
    agents:
      queue: dev-elastic-ci
  - name: "Check Generated Output"
    command: "./scripts/ci-check-generated.sh"
    key: "check-generated"
    timeout_in_minutes: 20
    agents:
      queue: dev-elastic-ci
