package config

const (
	ApiHostSchemaEnvVar      = "OKTAPAM_API_HOST"
	ApiKeySchemaEnvVar       = "OKTAPAM_KEY"
	ApiKeySecretSchemaEnvVar = "OKTAPAM_SECRET"
	TeamSchemaEnvVar         = "OKTAPAM_TEAM"

	ApiHostKey      = "oktapam_api_host"
	ApiKeyKey       = "oktapam_key"
	ApiKeySecretKey = "oktapam_secret"
	TeamKey         = "oktapam_team"

	DefaultAPIBaseURL = "https://app.scaleft.com"

	ProviderADCertificateObjectKey                 = "oktapam_ad_certificate_object"
	ProviderADCertificateRequestKey                = "oktapam_ad_certificate_request"
	ProviderADConnectionKey                        = "oktapam_ad_connection"
	ProviderADConnectionsKey                       = "oktapam_ad_connections"
	ProviderADTaskSettingsKey                      = "oktapam_ad_task_settings"
	ProviderADUserSyncTaskSettingsKey              = "oktapam_ad_user_sync_task_settings"
	ProviderADUserSyncTaskSettingsIDListKey        = "oktapam_ad_user_sync_task_settings_id_list"
	ProviderCurrentUser                            = "oktapam_current_user"
	ProviderCloudConnectionKey                     = "oktapam_cloud_connection"
	ProviderCloudConnectionsKey                    = "oktapam_cloud_connections"
	ProviderSudoCommandBundleKey                   = "oktapam_sudo_command_bundle"
	ProviderSudoCommandsBundlesKey                 = "oktapam_sudo_command_bundles"
	ProviderDatabaseKey                            = "oktapam_database"
	ProviderDatabasePasswordSettings               = "oktapam_database_password_settings"
	ProviderGatewaysKey                            = "oktapam_gateways"
	ProviderGatewaySetupTokenKey                   = "oktapam_gateway_setup_token"
	ProviderGatewaySetupTokensKey                  = "oktapam_gateway_setup_tokens"
	ProviderGroupKey                               = "oktapam_group"
	ProviderGroupsKey                              = "oktapam_groups"
	ProviderKubernetesClusterKey                   = "oktapam_kubernetes_cluster"
	ProviderKubernetesClusterConnectionKey         = "oktapam_kubernetes_cluster_connection"
	ProviderKubernetesClusterGroupKey              = "oktapam_kubernetes_cluster_group"
	ProviderPasswordSettingsKey                    = "oktapam_password_settings"
	ProviderProjectKey                             = "oktapam_project"
	ProviderProjectsKey                            = "oktapam_projects"
	ProviderProjectGroupKey                        = "oktapam_project_group"
	ProviderProjectGroupsKey                       = "oktapam_project_groups"
	ProviderResourceGroupKey                       = "oktapam_resource_group"
	ProviderResourceGroupsKey                      = "oktapam_resource_groups"
	ProviderResourceGroupProjectKey                = "oktapam_resource_group_project"
	ProviderResourceGroupProjectsKey               = "oktapam_resource_group_projects"
	ProviderResourceGroupServerEnrollmentTokenKey  = "oktapam_resource_group_server_enrollment_token"
	ProviderResourceGroupServerEnrollmentTokensKey = "oktapam_resource_group_server_enrollment_tokens"
	ProviderSecretKey                              = "oktapam_secret"
	ProviderSecretsKey                             = "oktapam_secrets"
	ProviderSecretFolderKey                        = "oktapam_secret_folder"
	ProviderSecretFoldersKey                       = "oktapam_secret_folders"
	ProviderSecurityPoliciesKey                    = "oktapam_security_policies"
	ProviderSecurityPolicyKey                      = "oktapam_security_policy"
	ProviderServerEnrollmentTokenKey               = "oktapam_server_enrollment_token"
	ProviderServerEnrollmentTokensKey              = "oktapam_server_enrollment_tokens"
	ProviderTeamSettingsKey                        = "oktapam_team_settings"
	ProviderUserGroupAttachmentKey                 = "oktapam_user_group_attachment"
	ProviderUserKey                                = "oktapam_user"
)
