provider:
  name: oktapam_framework_provider
  # This schema needs to exist in the OpenAPI spec!
  schema_ref: '#/components/schemas/TerraformProviderSchema'

resources:
  resource_server_checkout_settings:
    create:
      path: /v1/teams/{team_name}/resource_groups/{resource_group_id}/projects/{project_id}/server_checkout_settings
      method: PUT
    read:
      path: /v1/teams/{team_name}/resource_groups/{resource_group_id}/projects/{project_id}/server_checkout_settings
      method: GET
    update:
      path: /v1/teams/{team_name}/resource_groups/{resource_group_id}/projects/{project_id}/server_checkout_settings
      method: PUT
    delete:
      path: /v1/teams/{team_name}/resource_groups/{resource_group_id}/projects/{project_id}/server_checkout_settings
      method: PUT
    schema:
      ignores:
        - team_name