openapi: 3.0.2
info:
  contact:
    email: support@okta.com
    name: Okta Support
    url: https://support.okta.com
  description: The OPA API is a control plane used to request operations in Okta Privileged Access (formerly ScaleFT/Advanced Server Access)
  termsOfService: https://www.okta.com/agreements/
  title: Okta Privileged Access
  version: 1.0.0
servers:
  - url: https://{org_name}.pam.okta.com
    description: Production server
    variables:
      org_name:
        default: '{org_name}'
        description: The name of your Okta org
tags:
  - name: resource-groups
    x-displayName: Resource Groups
    description: |-
      An OPA Resource Group is a collection of Projects.
      See [Resource groups](https://help.okta.com/okta_help.htm?type=oie&id=ext-pam-resource-groups).
  - name: projects
    x-displayName: Projects
    description: |-
      An OPA Project is a collection of Resources that share settings.
paths:
  /v1/teams/{team_name}/resource_groups/{resource_group_id}/projects/{project_id}/server_checkout_settings:
    parameters:
      - $ref: '#/components/parameters/team_name'
      - $ref: '#/components/parameters/resource_group_id'
      - $ref: '#/components/parameters/project_id'
    get:
      summary: Retrieves the checkout settings configured for a project, specific to the server resource type.
      description: |-
        Retrieves the checkout settings configured for a project, specific to the server resource type.

        This endpoint requires one of the following roles: `resource_admin`, `delegated_resource_admin`, `security_admin`, `delegated_security_admin`.
      operationId: FetchResourceGroupServerBasedProjectCheckoutSettings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceCheckoutSettings'
      tags:
        - projects
    put:
      summary: Update the checkout settings configured for a project, specific to the server resource type
      description: |-
        Update the checkout settings configured for a project, specific to the server resource type

        This endpoint requires one of the following roles: `security_admin`, `delegated_security_admin`.
      operationId: UpdateResourceGroupServerBasedProjectCheckoutSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceCheckoutSettings'
      responses:
        '204':
          description: No Content
      tags:
        - projects
components:
  parameters:
    team_name:
      description: The name of your Team
      in: path
      name: team_name
      required: true
      schema:
        type: string
    resource_group_id:
      description: The UUID of a Resource Group
      in: path
      name: resource_group_id
      required: true
      schema:
        type: string
    project_id:
      description: The UUID of a Project
      in: path
      name: project_id
      required: true
      schema:
        type: string
  schemas:
    ResourceCheckoutSettings:
      type: object
      properties:
        checkout_required:
          description: Indicates whether a checkout is mandatory for accessing resources within the project. If `true`, checkout is enforced for all applicable resources by default. If `false`, checkout is not required, and resources are accessible without it.
          type: boolean
        checkout_duration_in_seconds:
          description: The duration in seconds for the checkout. If the checkout is enabled, the duration is the maximum time a user can access the resource before the checkout expires.
          type: integer
          maximum: 86400
          minimum: 900
          format: int32
        include_list:
          description: If provided, only the account identifiers listed are required to perform a checkout to access the resource. This list is only considered if `checkout_required` is set to `true`. Only one of `include_list` and `exclude_list` can be specified in a request since they are mutually exclusive.
          type: array
          items:
            type: string
        exclude_list:
          description: If provided, only the account identifiers listed are excluded from the checkout requirement. This list is only considered if `checkout_required` is set to `true`. Only one of `include_list` and `exclude_list` can be specified in a request since they are mutually exclusive.
          type: array
          items:
            type: string
      required:
        - checkout_required
    TerraformProviderSchema:
      type: object
      properties:
        oktapam_api_host:
          type: string
        oktapam_api_key:
          type: string
        oktapam_secret:
          type: string
        oktapam_team:
          type: string
      required:
        - oktapam_api_host
        - oktapam_api_key
        - oktapam_secret
        - oktapam_team
